apiVersion: apps/v1
kind: Deployment
metadata:
  name: niles
spec:
  template:
    spec:
      containers:
        - name: niles
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
