apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: niles-dev

resources:
  - ../../base

images:
  - name: niles
    newName: ghcr.io/marknygaard/niles
    newTag: latest

configMapGenerator:
  - name: niles-config
    behavior: replace
    files:
      - niles.toml

patches:
  - path: deployment-dev.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: dev
    includeSelectors: true
