[package]
name = "niles-config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
niles-core.workspace = true
niles-scheduler.workspace = true
niles-recognition.workspace = true
niles-notifications.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
