apiVersion: apps/v1
kind: Deployment
metadata:
  name: niles
spec:
  template:
    spec:
      containers:
        - name: niles
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /data
