apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: niles

resources:
  - ../../base

images:
  - name: niles
    newName: ghcr.io/marknygaard/niles
    newTag: latest

configMapGenerator:
  - name: niles-config
    behavior: replace
    files:
      - niles.toml

patches:
  - path: deployment-prod.yaml
  - path: volume-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: niles

labels:
  - pairs:
      app.kubernetes.io/instance: production
    includeSelectors: true
