[package]
name = "niles-recognition"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ndarray.workspace = true
ort.workspace = true
realfft.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
fs2.workspace = true

[dev-dependencies]
tempfile.workspace = true
rand.workspace = true
rand_chacha.workspace = true
